.\"
.\" Copyright (c) 2016, 2019 Tobias Kortkamp <t@tobik.me>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
.\" SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
.\" OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
.\" CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd April 18, 2020
.Dt SIMPLESTROKE 1
.Os
.Sh NAME
.Nm simplestroke
.Nd "detect mouse gestures"
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
detects mouse gestures.  There are twelve pre-defined mouse gestures
you can choose from.
.Pp
With no arguments
.Nm
starts in gesture detection mode.  Draw your gesture and then confirm by
clicking any mouse button.
.Pp
.Nm
reacts on the release of mouse buttons.  This makes it possible to
start
.Nm
from your window manager while pressing down a mouse button and start
gesture analysis after releasing it.
.Pp
.Nm
prints the name of the detected gesture, if any.  The output can then
be used in a simple shell script to execute commands.
.Sh GESTURES
The following gestures are supported.  The names are derived from the
direction you would draw them in.
.Ss ARROW GESTURES
.Bd -literal
ArrowUp		^
ArrowDown	v
ArrowLeft	<
ArrowRight	>
.Ed
.Ss STRAIGHT LINE GESTURES
.Bd -literal
TopDown 	| (start at top)
DownTop		|
LeftRight	- (left to right)
RightLeft	- (right to left)
.Ed
.Ss DIAGONAL GESTURES
.Bd -literal
TopLeftDown	\\ (start at top)
TopRightDown	/ (start at top)
DownLeftTop	\\
DownRightTop	/
.Ed
.Ss "Z" GESTURES
.Bd -literal
LeftZ
RightZ
.Ed
.Ss SQUARE GESTURES
.Bd -literal
SquareLeft	("clockwise" square)
SquareRight	("counterclockwise" square)
.Ed
.Sh EXAMPLES
The following examples assume that
.Pa simplestroke.sh
is the shell script you call
.Nm
from:
.Bd -literal -offset indent
#!/bin/sh
case $(simplestroke) in
    ArrowUp)
    ;;
    ArrowDown)
    ;;
    ArrowLeft)
    ;;
    ArrowRight)
    ;;
    TopDown)
    ;;
    DownTop)
    ;;
    LeftRight)
    ;;
    RightLeft)
    ;;
    TopLeftDown)
    ;;
    TopRightDown)
    ;;
    DownLeftTop)
    ;;
    DownRightTop)
    ;;
    LeftZ)
    ;;
    RightZ)
    ;;
    SquareLeft)
    ;;
    SquareRight)
    ;;
    *)
        exit 1
esac
.Ed
.Pp
To start detection under i3 while holding down the 9th mouse button
add this to your
.Pa ~/.config/i3/config:
.Bd -literal -offset 2n
bindsym --whole-window button9 exec simplestroke.sh
.Ed
.Pp
The right mouse button can be determined via
.Xr xev 1 .
.Pp
For Sway add this to your
.Pa ~/.config/sway/config :
.Bd -literal -offset 2n
bindsym --whole-window BTN_EXTRA exec simplestroke.sh
.Ed
.Pp
The right BTN_* values can be determined via
.Xr libinput-debug-events 1 .
.Pp
Hold the mouse button and after you are finished drawing your gesture,
release it.
.Sh AUTHORS
.An Tobias Kortkamp Aq Mt tobik@FreeBSD.org
.Pp
.Nm
is inspired and based on \fBeasystroke\fP 0.6.0 written by Thomas Jaeger
.Aq Lk https://github.com/thjaeger/easystroke .
