.\"
.\" Copyright (c) 2016 Tobias Kortkamp <t@tobik.me>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
.\" SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
.\" OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
.\" CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd September 2, 2016
.Dt SIMPLESTROKE-DAEMON 1
.Os
.Sh NAME
.Nm simplestroke-daemon
.Nd "wait for mouse button clicks"
.Sh SYNOPSIS
.Nm
.Fl c Ar command
.Op Fl b Ar button
.Op Fl m Ar modifier
.Sh DESCRIPTION
.Nm
detects mouse buttons clicks and then runs the specified command.
.Pp
If not specified
.Ar button
defaults to 3 (the right mouse button).
.Pp
.Ar modifier
can be one of the following values: mod1, mod2, mod3, mod4, mod5,
control, shift, lock.
.Sh EXAMPLES
To run the
.Pa simplestroke.sh
script when mouse button 9 is pressed
.Bd -literal -offset 2n
.Ic simplestroke-daemon -c simplestroke.sh -b 3
.Ed
.Pp
To wait for mouse button 3 clicks when a modifier key (here the Super
key) is pressed:
.Bd -literal -offset 2n
.Ic simplestroke-daemon -c simplestroke.sh -b 3 -m mod4
.Ed
.Sh SEE ALSO
.Xr simplestroke 1
.Sh AUTHORS
.An Tobias Kortkamp Aq Mt t@tobik.me
